services:
  - type: web
    name: job-scrapper
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONPATH
        value: "/backend"
