"""add_scraping_history_table

Revision ID: 07a7a1635452
Revises: ff62893dc014
Create Date: 2025-02-18 00:33:10.780324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07a7a1635452"
down_revision: Union[str, None] = "ff62893dc014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scraping_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("jobs_found", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add any new columns to jobs table if needed
    op.add_column("jobs", sa.Column("category", sa.String(100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scraping_history")

    # Remove added columns from jobs table
    op.drop_column("jobs", "category")
    # ### end Alembic commands ###
