"""add job sources

Revision ID: 19b47ea441c5
Revises: 89c1f1078482
Create Date: 2025-03-01 18:32:45.426876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b47ea441c5'
down_revision: Union[str, None] = '89c1f1078482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraping_config', sa.JSON(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('scraping_history', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scraping_history', 'job_sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraping_history', type_='foreignkey')
    op.drop_column('scraping_history', 'source_id')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
