"""added the onboarding logic

Revision ID: 31eac5002b8b
Revises: 8ebf4ba2100c
Create Date: 2025-03-11 22:42:45.188227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eac5002b8b'
down_revision: Union[str, None] = '8ebf4ba2100c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_status', sa.Enum('INCOMPLETE', 'IN_PROGRESS', 'COMPLETED', name='userprofilestatus'), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('professional_title', sa.String(length=255), nullable=True),
    sa.Column('career_stage', sa.String(length=100), nullable=True),
    sa.Column('domains', sa.String(length=500), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index('idx_job_experience', 'jobs', ['experience'], unique=False)
    op.create_index('idx_job_location', 'jobs', ['location'], unique=False)
    op.create_index('idx_job_type', 'jobs', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_job_type', table_name='jobs')
    op.drop_index('idx_job_location', table_name='jobs')
    op.drop_index('idx_job_experience', table_name='jobs')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
