"""added Proxy table

Revision ID: 64c0bbf47583
Revises: bda70af323f7
Create Date: 2025-03-18 23:14:08.489026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c0bbf47583'
down_revision: Union[str, None] = 'bda70af323f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxies', sa.Column('city', sa.String(), nullable=True))
    op.add_column('proxies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('proxies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('proxies', sa.Column('total_requests', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('successful_requests', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('failed_requests', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('proxies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('proxies', sa.Column('supports_ssl', sa.Boolean(), nullable=True))
    op.add_column('proxies', sa.Column('supports_streaming', sa.Boolean(), nullable=True))
    op.add_column('proxies', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('proxies', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('proxies', sa.Column('reliability_score', sa.Float(), nullable=True))
    op.add_column('proxies', sa.Column('performance_score', sa.Float(), nullable=True))
    op.alter_column('proxies', 'protocol',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('HTTP', 'HTTPS', 'SOCKS4', 'SOCKS5', name='proxyprotocol'),
               nullable=False)
    op.alter_column('proxies', 'anonymity',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('TRANSPARENT', 'ANONYMOUS', 'HIGH_ANONYMITY', name='anonymitylevel'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proxies', 'anonymity',
               existing_type=sa.Enum('TRANSPARENT', 'ANONYMOUS', 'HIGH_ANONYMITY', name='anonymitylevel'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('proxies', 'protocol',
               existing_type=sa.Enum('HTTP', 'HTTPS', 'SOCKS4', 'SOCKS5', name='proxyprotocol'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('proxies', 'performance_score')
    op.drop_column('proxies', 'reliability_score')
    op.drop_column('proxies', 'source_type')
    op.drop_column('proxies', 'provider')
    op.drop_column('proxies', 'supports_streaming')
    op.drop_column('proxies', 'supports_ssl')
    op.drop_column('proxies', 'updated_at')
    op.drop_column('proxies', 'created_at')
    op.drop_column('proxies', 'failed_requests')
    op.drop_column('proxies', 'successful_requests')
    op.drop_column('proxies', 'total_requests')
    op.drop_column('proxies', 'longitude')
    op.drop_column('proxies', 'latitude')
    op.drop_column('proxies', 'city')
    # ### end Alembic commands ###
