"""Initial migration

Revision ID: 74cb5090ceec
Revises: 
Create Date: 2025-02-16 02:26:45.326781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cb5090ceec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_id', table_name='jobs')
    op.drop_index('ix_jobs_posting_date', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('salary', sa.VARCHAR(length=100), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=100), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('detail_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('apply_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('posting_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail_url')
    )
    op.create_index('ix_jobs_posting_date', 'jobs', ['posting_date'], unique=False)
    op.create_index('ix_jobs_id', 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###
