"""parsed_resume table

Revision ID: b1e71d9a787c
Revises: f437d16c6e01
Create Date: 2025-05-01 01:18:28.934729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e71d9a787c'
down_revision: Union[str, None] = 'f437d16c6e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_resumes_id'), 'parsed_resumes', ['id'], unique=False)
    op.add_column('proxies', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('proxies', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('country', sa.String(), nullable=True))
    op.add_column('proxies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('proxies', sa.Column('success_rate', sa.Float(), nullable=True))
    op.add_column('proxies', sa.Column('avg_response_time', sa.Float(), nullable=True))
    op.add_column('proxies', sa.Column('consecutive_failures', sa.Integer(), nullable=True))
    op.add_column('proxies', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_index(op.f('ix_proxies_ip'), 'proxies', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxies_ip'), table_name='proxies')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_column('proxies', 'last_checked')
    op.drop_column('proxies', 'consecutive_failures')
    op.drop_column('proxies', 'avg_response_time')
    op.drop_column('proxies', 'success_rate')
    op.drop_column('proxies', 'is_active')
    op.drop_column('proxies', 'country')
    op.drop_column('proxies', 'port')
    op.drop_column('proxies', 'ip')
    op.drop_index(op.f('ix_parsed_resumes_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    # ### end Alembic commands ###
